name: async_queue
description: This dart package ensure your pack of async tasks execute in order, one after the other.
version: 2.0.0-dev.2
homepage: https://github.com/samderlust/async_queue

environment:
  sdk: ">=2.18.2 <4.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

topics:
  - async
  - queue
  - async-queue
